<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <ApplicationIcon>Assets/wolpertinger.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <ProjectReference Include="../Wolpertinger.Presentation/Wolpertinger.Presentation.csproj" />
    <ProjectReference Include="../Wolpertinger.Presentation.Windows/Wolpertinger.Presentation.Windows.csproj" />
    <ProjectReference Include="../Wolpertinger.Product.Contracts/Wolpertinger.Product.Contracts.csproj" />
    <AvaloniaResource Include="Assets/**" />
  </ItemGroup>
</Project>
