<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Wolpertinger.Presentation/Wolpertinger.Presentation.csproj" />
  </ItemGroup>
</Project>
